chats-lab:
  sources-dir: C:\Users\ivanl\Dropbox\Чатики\New
  output-dir: F:\chatsLab\

  # Messages per year to count user as active
  active-threshold-year: 300
  active-threshold-overall: 300
  participant-ids: 9397429,5804152,1538548,23831182,6313109,72632602,20630922,19707045

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatsLab
    username: postgres
    password:
  jpa:
    generate-ddl: true