chats-lab:
  sources-dir: C:\Users\ivanl\Dropbox\Чатики\New
  output-dir: F:\chatsLab\

  # Messages per year to count user as active
  active-threshold-year: 300
  active-threshold-overall: 300

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatsLab
    username: postgres
    password:
  jpa:
    generate-ddl: true